services:
  postgres:
    image: postgres:16-alpine
    container_name: flick_pg_dev
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env.development
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7-alpine
    container_name: flick_redis_dev
    ports:
      - '${REDIS_PORT:-6379}:6379'
    env_file:
      - .env.development
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ALLOW_EMPTY_PASSWORD=yes
